import { Recipe, Category } from "./types";

export const categories: Category[] = [
  {
    id: "vegetables",
    name: "Vegetables",
    image:
      "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&h=300&fit=crop&crop=center",
    description: "Fresh vegetable recipes from your garden",
    recipeCount: 25,
  },
  {
    id: "herbs",
    name: "Herbs",
    image:
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop&crop=center",
    description: "Aromatic herb-based dishes",
    recipeCount: 18,
  },
  {
    id: "fruits",
    name: "Fruits",
    image:
      "https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=400&h=300&fit=crop&crop=center",
    description: "Sweet and savory fruit recipes",
    recipeCount: 22,
  },
  {
    id: "salads",
    name: "Salads",
    image:
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop&crop=center",
    description: "Fresh garden salads",
    recipeCount: 15,
  },
];

export const recipes: Recipe[] = [
  {
    id: "1",
    title: "Garden Fresh Caprese Salad",
    description:
      "A classic Italian salad featuring fresh tomatoes, mozzarella, and basil from your garden",
    image:
      "https://images.unsplash.com/photo-1551782450-17144efb9c50?w=600&h=400&fit=crop&crop=center",
    prepTime: "15 mins",
    cookTime: "0 mins",
    servings: 4,
    difficulty: "Easy",
    category: "salads",
    ingredients: [
      "4 large ripe tomatoes",
      "8 oz fresh mozzarella",
      "1/4 cup fresh basil leaves",
      "3 tbsp extra virgin olive oil",
      "2 tbsp balsamic vinegar",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Slice tomatoes and mozzarella into 1/4 inch thick rounds",
      "Arrange alternating slices of tomato and mozzarella on a platter",
      "Tuck fresh basil leaves between the slices",
      "Drizzle with olive oil and balsamic vinegar",
      "Season with salt and pepper",
      "Serve immediately",
    ],
    tags: ["vegetarian", "gluten-free", "quick"],
    author: "Garden Chef",
    rating: 4.8,
    reviews: 124,
  },
  {
    id: "2",
    title: "Herb-Crusted Roasted Vegetables",
    description: "Seasonal vegetables roasted with a fragrant herb crust",
    image:
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&h=400&fit=crop&crop=center",
    prepTime: "20 mins",
    cookTime: "35 mins",
    servings: 6,
    difficulty: "Easy",
    category: "vegetables",
    ingredients: [
      "2 lbs mixed vegetables (carrots, zucchini, bell peppers)",
      "1/4 cup olive oil",
      "3 tbsp mixed fresh herbs (rosemary, thyme, oregano)",
      "4 cloves garlic, minced",
      "1/2 cup breadcrumbs",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Preheat oven to 425°F (220°C)",
      "Cut vegetables into 1-inch pieces",
      "Mix herbs, garlic, and breadcrumbs in a bowl",
      "Toss vegetables with olive oil, salt, and pepper",
      "Arrange on a baking sheet and sprinkle with herb mixture",
      "Roast for 30-35 minutes until tender and golden",
    ],
    tags: ["vegetarian", "healthy", "roasted"],
    author: "Garden Chef",
    rating: 4.6,
    reviews: 89,
  },
  {
    id: "3",
    title: "Fresh Basil Pesto Pasta",
    description: "Homemade pesto using fresh basil from your garden",
    image:
      "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=600&h=400&fit=crop&crop=center",
    prepTime: "15 mins",
    cookTime: "10 mins",
    servings: 4,
    difficulty: "Easy",
    category: "herbs",
    ingredients: [
      "2 cups fresh basil leaves",
      "1/2 cup pine nuts",
      "3 cloves garlic",
      "1/2 cup grated Parmesan cheese",
      "1/2 cup olive oil",
      "12 oz pasta",
      "Salt to taste",
    ],
    instructions: [
      "Cook pasta according to package directions",
      "In a food processor, combine basil, pine nuts, and garlic",
      "Pulse until finely chopped",
      "Add Parmesan cheese and pulse to combine",
      "With processor running, slowly add olive oil",
      "Season with salt",
      "Toss pesto with cooked pasta and serve",
    ],
    tags: ["vegetarian", "pasta", "herbs"],
    author: "Garden Chef",
    rating: 4.9,
    reviews: 156,
  },
  {
    id: "4",
    title: "Garden Vegetable Soup",
    description: "A hearty soup packed with fresh garden vegetables",
    image:
      "https://images.unsplash.com/photo-1547592180-85f173990554?w=600&h=400&fit=crop&crop=center",
    prepTime: "25 mins",
    cookTime: "45 mins",
    servings: 6,
    difficulty: "Medium",
    category: "vegetables",
    ingredients: [
      "2 tbsp olive oil",
      "1 onion, diced",
      "3 cloves garlic, minced",
      "2 carrots, diced",
      "2 celery stalks, diced",
      "1 zucchini, diced",
      "1 can diced tomatoes",
      "6 cups vegetable broth",
      "1 cup fresh herbs (parsley, thyme)",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Heat olive oil in a large pot over medium heat",
      "Add onion and garlic, cook until fragrant",
      "Add carrots and celery, cook for 5 minutes",
      "Add zucchini and tomatoes, cook for 3 minutes",
      "Pour in vegetable broth and bring to a boil",
      "Reduce heat and simmer for 30 minutes",
      "Stir in fresh herbs and season with salt and pepper",
      "Serve hot with crusty bread",
    ],
    tags: ["vegetarian", "soup", "healthy"],
    author: "Garden Chef",
    rating: 4.7,
    reviews: 98,
  },
  {
    id: "5",
    title: "Strawberry Basil Lemonade",
    description:
      "Refreshing summer drink with garden-fresh strawberries and basil",
    image:
      "https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=600&h=400&fit=crop&crop=center",
    prepTime: "20 mins",
    cookTime: "0 mins",
    servings: 6,
    difficulty: "Easy",
    category: "fruits",
    ingredients: [
      "2 cups fresh strawberries",
      "1/2 cup fresh basil leaves",
      "1 cup fresh lemon juice",
      "1/2 cup sugar",
      "4 cups cold water",
      "Ice cubes",
    ],
    instructions: [
      "In a blender, puree strawberries and basil",
      "Strain mixture through a fine mesh sieve",
      "In a pitcher, combine strawberry-basil puree with lemon juice",
      "Add sugar and stir until dissolved",
      "Add cold water and mix well",
      "Serve over ice with fresh basil garnish",
    ],
    tags: ["drinks", "refreshing", "summer"],
    author: "Garden Chef",
    rating: 4.5,
    reviews: 67,
  },
  {
    id: "6",
    title: "Roasted Herb Potatoes",
    description: "Crispy roasted potatoes seasoned with fresh garden herbs",
    image:
      "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=600&h=400&fit=crop&crop=center",
    prepTime: "15 mins",
    cookTime: "40 mins",
    servings: 4,
    difficulty: "Easy",
    category: "vegetables",
    ingredients: [
      "2 lbs baby potatoes",
      "3 tbsp olive oil",
      "2 tbsp fresh rosemary",
      "2 tbsp fresh thyme",
      "4 cloves garlic, minced",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Preheat oven to 425°F (220°C)",
      "Cut potatoes in half",
      "Mix olive oil with herbs and garlic",
      "Toss potatoes with herb mixture",
      "Season with salt and pepper",
      "Roast for 35-40 minutes until golden and crispy",
      "Serve immediately",
    ],
    tags: ["vegetarian", "side-dish", "roasted"],
    author: "Garden Chef",
    rating: 4.6,
    reviews: 112,
  },
];
